[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "DropDaDeuce"
name = "K9Patrol_IL2Cpp"
versionNumber = "1.0.0"
description = "Time no longer stops at 4AM. Also adds a config option to set the day speed multiplier."
websiteUrl = "https://github.com/DropDaDeuce/K9-Patrol"
containsNsfwContent = false
[package.dependencies]
LavaGang-MelonLoader = "0.7.1"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./Packages"

[[build.copy]]
source = "./TNS_Project/bin/IL2CPP/net6.0/K9Patrol_IL2Cpp.dll"
target = "/"

[[build.copy]]
source = "./CHANGELOG.md"
target = "/"

[publish]
communities = [ "schedule-i", ]
[publish.categories]
lethal-company = [ "Mods", "IL2CPP", ]